chore: Obscured and OffScreen Views Policy
dequelabs/axe-android pull request #130
Opened 2021-01-18 19:19 UTC by devchan4188

Closes: [issue](https://app.zenhub.com/workspaces/mobile-5ccf5c056202ac26f233076a/issues/dequelabs/axe-android-app/227)

## Requester Review Items

- [x] Ensure the Pull Request is into develop.
- [x] Test coverage has not gone down.
- [x] Documentation updated or not needed. (Wiki, Issues, etc)
- [x] Angular Type leads to proper Semantic Version.

## Dev Team Review Items

To be filled out by @dequelabs/mobile.

- [ ] Ensure the Requester did not lie. Chastise them politely if they did.
- [ ] Code Quality review.
- [ ] Changes to Axe*.java classes are minimal, appropriate, and versioned properly.
  - [ ] Serialized Axe objects have not changed.
  - [ ] Public API has not changed.

## Code Owner Review Items

To be filled out by @dequelabs/mobileadmin.

- [ ] Any Rules package changes lead to proper Semantic Version.
- [ ] Security Review.

## Merger Review Items

- [ ] Ensure commit message matches title before squashing.

2021-02-02 21:20 UTC, chriscm2006 requested changes
I almost changed it myself, but your description was confusing enough I wasn't sure what the proper description was.

2021-02-02 21:20 UTC, chriscm2006 commented on src/main/java/com/deque/axe/android/AxeRuleResult.java
> +   * True when result belongs to a view not visible to user.
This description is confusing.

2021-02-02 22:11 UTC, kateowens12 approved these changes

2021-02-03 17:40 UTC, chriscm2006 approved these changes

2021-02-03 17:41 UTC, merged